name: Linting, Testing, Building

on: 
  push:
    branches: [main] # Убедитесь, что у вас именно main, а не master
  pull_request:
    branches: [main]

jobs:
  pipeline: # Исправлено с "pipline"
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [17.x] # Используем актуальные версии Node.js

    steps:
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build production project
        run: npm run build:prod
      - name: Lint TypeScript
        run: npm run lint:ts
      - name: Lint CSS
        run: npm run lint:scss 
      - name: Run unit tests
        run: npm run test:unit