name: Linting, Testing, Building
on: 
  push:
    branches: [master] # Убедитесь, что у вас именно main, а не master
  pull_request:
    branches: [master]
jobs:
  pipeline: # Исправлено с "pipline"
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [17.x] # Используем актуальные версии Node.js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: Lint TypeScript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
        if: always() 
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()